working_directory   = "Projects"

[font]
size = 13.0

[font.bold]
family = "Hack Nerd Font Mono"
style = "Regular"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Regular"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[window]
opacity = 0.95

[shell]
program = "/Users/misaelaguayo/.nix-profile/bin/nu"
