"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
version = 3

[[blocks]]
type = "rprompt"

  [[blocks.segments]]
  foreground = "#007ACC"
  template = " {{ .CurrentDate | date .Format }} "
  style = "plain"
  type = "time"

    [blocks.segments.properties]
    time_format = "15:04:05"

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

  [[blocks.segments]]
  background = "#ffb300"
  foreground = "#ffffff"
  leading_diamond = ""
  template = " {{ .UserName }} "
  style = "diamond"
  trailing_diamond = ""
  type = "session"

  [[blocks.segments]]
  background = "#61AFEF"
  foreground = "#ffffff"
  powerline_symbol = ""
  template = " {{ .Path }} "
  exclude_folders = [ "/super/secret/project" ]
  style = "powerline"
  type = "path"

    [blocks.segments.properties]
    style = "folder"

  [[blocks.segments]]
  background = "#2e9599"
  background_templates = [
  "{{ if or (.Working.Changed) (.Staging.Changed) }}#f36943{{ end }}",
  "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#a8216b{{ end }}",
  "{{ if gt .Ahead 0 }}#35b5ff{{ end }}",
  "{{ if gt .Behind 0 }}#f89cfa{{ end }}"
]
  foreground = "#193549"
  foreground_templates = [ "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#ffffff{{ end }}" ]
  powerline_symbol = ""
  template = " {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }} "
  style = "powerline"
  type = "git"

    [blocks.segments.properties]
    branch_max_length = 25
    fetch_status = true

  [[blocks.segments]]
  background = "#00897b"
  background_templates = [ "{{ if gt .Code 0 }}#e91e63{{ end }}" ]
  foreground = "#ffffff"
  template = "<parentBackground></>  "
  style = "diamond"
  trailing_diamond = ""
  type = "status"

    [blocks.segments.properties]
    always_enabled = true
