[user]
name = "Misael Aguayo"
email = "maguayo@armlend.com"

[ui]
diff-editor = ["nvim", "-c", "DiffEditor $left $right $output"]
diff-formatter = "delta"
merge-editor = "mergiraf"
conflict-marker-style = "git"

[revset-aliases]
immutable_heads = "builtin_immutable_heads() | (remote_bookmarks())"

[aliases]
# Find the closest ancestor with a bookmark pointing at it, and move it to the
# parent of the working copy.
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]
