[user]
name = "Misael Aguayo"
email = "aguayo.misael@gmail.com"

[ui]
diff-editor = ["nvim", "-c", "DiffEditor $left $right $output"]
diff-formatter = "delta"
merge-editor = "mergiraf"
conflict-marker-style = "git"

[revset-aliases]
immutable_heads = "remote_bookmarks()"
